version: '3'

services: 
  nexus:
    container_name: 'nexus'
    image: 'sonatype/nexus3:3.25.1'
    restart: 'always'
    volumes: 
      - './nexus-data:/nexus-data'
      - './nexus-backup:/nexus-backup'
    networks:
      - 'reverse_proxy_network'
      - 'ldap_network'

networks:
  reverse_proxy_network:
    external: true
  ldap_network:
    external: true