version: '3'

services: 

  jumpaku-othello:
    container_name: 'jumpaku-othello'
    image: 'jumpaku/jumpaku-othello'
    restart: 'always'
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    external: true