version: '3'

services: 

  jumpaku-othello:
    image: jumpaku/jumpaku-othello
    container_name: 'jumpaku-othello'
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    external: true