version: '3'

services: 
  rainloop:
    image: 'hardware/rainloop'
    container_name: 'rainloop'
    volumes:
      - './rainloop_data/:/rainloop/data'
    environment: 
      - 'LOG_TO_STDOUT=true'
    networks: 
      - 'reverse_proxy_network'
      
networks:
  reverse_proxy_network:
    external: true
