version: '3'

services: 
  rainloop:
    image: 'hardware/rainloop'
    container_name: 'rainloop'
    volumes:
      - './rainloop/data/:/rainloop/data'
    networks: 
      - 'reverse_proxy_network'
      
networks:
  reverse_proxy_network:
    external: true
