version: '3'

services: 

  reverse_proxy:
    image: 'steveltn/https-portal:1'
    container_name: 'reverse_proxy'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './certs/:/var/lib/https-portal/'
    networks:
      - 'reverse_proxy_network'
    # restart: always
    env_file: 
      - 'reverse_proxy.env'

networks:
  reverse_proxy_network:
    external: true
