version: '3'

services: 

  reverse_proxy:
    container_name: 'reverse_proxy'
    image: 'jumpaku/nginx-letsencrypt-reverse-proxy:release-v1.0.1'
    restart: 'always'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './certs/:/certificates/'
    networks:
      - 'reverse_proxy_network'
    environment: 
      - "RENEW_SCHED=13 0 * * sat"
      - "STAGE=production"
      - "DOMAINS=\
        test.jumpaku.net, \
        nexus.jumpaku.net -> http://nexus:8081, \
        gitea.jumpaku.net -> http://gitea:3000, \
        nextcloud.jumpaku.net -> http://nextcloud:80, \
        othello.jumpaku.net -> http://jumpaku-othello:8080, \
        rainloop.jumpaku.net -> http://rainloop:8888, \
        smtps.jumpaku.net, \
        imaps.jumpaku.net"

networks:
  reverse_proxy_network:
    external: true
