version: '3'

services:
  nextcloud_mariadb:
    image: mariadb
    container_name: nextcloud_mariadb
    volumes:
      - ./nextcloud_mariadb/data/:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=<mysql_root_password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=<admin_password>
    # restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    depends_on:
      - nextcloud_mariadb
    volumes:
      - ./nextcloud/html/:/var/www/html/
    networks: 
      - default
      - reverse_proxy_network
    # restart: always

networks:
  reverse_proxy_network:
    external: true