version: '3'

services:

  nextcloud:
    image: 'nextcloud:16'
    container_name: 'nextcloud'
    depends_on:
      - 'nextcloud_mariadb'
    volumes:
      - './nextcloud/html/:/var/www/html/'
    networks: 
      - 'db_network'
      - 'reverse_proxy_network'
      - 'ldap_network'
    # restart: always
    environment: 
      - 'NEXTCLOUD_ADMIN_USER=nextcloud_admin'
      - 'NEXTCLOUD_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}'
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_HOST=nextcloud_mariadb'
    ports: 
      - '8080:80'

  nextcloud_mariadb:
    image: 'mariadb'
    container_name: 'nextcloud_mariadb'
    volumes:
      - './nextcloud_mariadb/data/:/var/lib/mysql'
    networks:
      - 'db_network'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    # restart: always

networks:
  reverse_proxy_network:
    external: true
  ldap_network:
    external: true
  db_network:
