version: '3'

services: 
  www:
    image: nginx:alpine
    container_name: www
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www/:/var/www/
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    external: true

