version: '3'

services:
  mysql:
    image: mysql:5
    volumes:
      - ./aurora/DB:/docker-entrypoint-initdb.d
    #ports:
    #  - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=aurora
    networks:
        - aurora_network

  web:
    build: ./aurora/Web Interface
    image: docker.pkg.github.com/pushkar8723/aurora/web
    ports:
      - 8080:80
    environment:
      - AURORA_SQL_USER=root
      - AURORA_SQL_PASS=aurora
      - AURORA_SQL_DB=aurora_main
      - AURORA_SQL_HOST=mysql
    volumes:
      - ./aurora/conf:/etc/apache2/sites-enabled
    networks:
        - reverse_proxy_network
        - aurora_network

  judge:
    build: ./aurora/Judge
    image: docker.pkg.github.com/pushkar8723/aurora/judge
    
    #ports:
    #  - 8723:8723
    environment:
      - AURORA_SQL_HOSTNAME=mysql
      - AURORA_SQL_USERNAME=root
      - AURORA_SQL_PASSWORD=aurora
      - AURORA_SQL_DATABASE=aurora_main
    networks:
        - aurora_network
networks:
    reverse_proxy_network:
        external: true
    aurora_network:
      