version: '3'

services: 

  openldap:
    build:
      context: ./openldap
      dockerfile: Dockerfile-openldap
    container_name: openldap
    networks: 
      - default
      - ldap_network
    environment:
      - "LDAP_ROOT_PW=${LDAP_ROOT_PW}"

  ldap_init:
    build:
      context: ./ldap_init
      dockerfile: Dockerfile-ldap_init
    container_name: ldap_init
    depends_on: 
      - openldap
    environment: 
      - "LDAP_ROOT_PW=${LDAP_ROOT_PW}"
    networks: 
      - default
    volumes:
      - "./ldap_init/data/:/home/data/"

networks:
  ldap_network:
    external: true
