version: '3'

services: 

  openldap:
    image: osixia/openldap
    container_name: openldap
    networks: 
      - ldap_network
    volumes:
      - "./openldap/ldap/:/var/lib/ldap/"
      - "./openldap/slapd.d/:/etc/ldap/slapd.d"
    environment:
      - "LDAP_ORGANISATION=Jumpaku"
      - "LDAP_DOMAIN=jumpaku.net"
      - "LDAP_ADMIN_PASSWORD=<ldap admin password>"

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    networks: 
      - ldap_network
      - reverse_proxy_network
    environment:
      - 'PHPLDAPADMIN_LDAP_HOSTS=openldap'
      - 'PHPLDAPADMIN_HTTPS=false'
    depends_on:
      - openldap

networks:
  reverse_proxy_network:
    external: true
  ldap_network:
    external: true
