version: '3'

services: 

  openldap:
    build: './openldap'
    container_name: 'openldap'
    networks: 
      - 'ldap_network'
    environment:
      - "LDAP_ROOT_PW=${LDAP_ROOT_PW}"

  ldap-client:
    build: './ldap-client'
    container_name: 'ldap-client'
    environment: 
      - "LDAP_ROOT_PW=${LDAP_ROOT_PW}"
    networks: 
      - 'ldap_network'
    volumes:
      - './users.ldif:/home/data/users.ldif:ro'

networks:
  ldap_network:
    external: true


