version: '3'

services: 
  dovecot:
    build: './dovecot/'
    container_name: 'dovecot'
    volumes: 
      - './dovecot/data/:/data/'
    networks: 
      - 'ldap_network'

  postfix:
    build: './postfix/'
    container_name: 'postfix'
    volumes: 
      - './postfix/data/:/data/'
    networks: 
      - 'ldap_network'
    
  rainloop:
    image: 'hardware/rainloop'
    container_name: 'rainloop'
    volumes:
      - './rainloop/data/:/rainloop/data'
    networks: 
      - 'reverse_proxy_network'
  
  mail_test:
    build: './mail_test'
    container_name: 'mail_test'
    networks: 
      - 'ldap_network'

networks:
  reverse_proxy_network:
    external: true
  ldap_network:
    external: true
