version: '3'

services: 
  dovecot:
    build: './dovecot/'
    container_name: 'dovecot'
    volumes: 
      - './dovecot/:/data/'
    networks: 
      - 'ldap_network'

  postfix:
    build: './postfix/'
    container_name: 'postfix'
    volumes: 
      - './postfix/:/data/'
    networks: 
      - 'ldap_network'
    command: ["/data/start.sh"]
    
  rainloop:
    image: 'hardware/rainloop'
    container_name: 'rainloop'
    volumes:
      - './rainloop/data/:/rainloop/data'
    networks: 
      - 'reverse_proxy_network'

networks:
  reverse_proxy_network:
    external: true
  ldap_network:
    external: true
